### PR TITLE
Implement templateless PCR

### PR DESCRIPTION
**Pull request by dgruano**
Hi @manulera ,

Following or discussion on #105, I went ahead and implemented this functionality. Only thing missing are tests ( I will work on them). Do you think the way I used the new Assembly is okay? Would you do it differently?

Changes:
- Add new API endpoint
- Add new model
- Add new assembly subclass specific for Templateless PCR
- Add notebook for debugging and testing

See frontend changes here https://github.com/manulera/ShareYourCloning_frontend/pull/118

### CODE REVIEW

**Comment by manulera** [comment]
Also, I don't know if you saw, but I recently added some pre-commit hooks to standardise the style of the code. To use them:

```bash
poetry install  --with dev --with test
pre-commit install
```

Now when you commit locally, style changes will be applied (if style changes are needed, it prevents you from committing, and applies the style as untracked changes that you have to add and then commit again).

**Comment by dgruano** [comment]
Everything okay with the changes you added, merged.

I should now have installed the pre-commit hooks to properly match the linting style!

**Comment by dgruano** [comment]
Some comments for the cases you mentioned

> ```
> Primers match entirely
> 
> ACGTACGT
> TGCATGCA
> ``` 

I have done this in the lab, just throwing two complementary ssDNA oligos, heat at 96 ºC and let it cool so they anneal. So I'd say this is a special case that is not a PCR _per se_ but the spirit is the same: you get dsDNA from ssDNA oligos that you synthesized somehow. I think our current implementation supports this case (I'll add the test nevertheless).
> ```
> A case like this, what should happen?
> 
> AAcccccAA
>   GGGGG
> ```

I have not done this, but I would expect it just results in something like:
```
AAcccccAA
ttGGGGG
```

So the resulting DNA would have this overhang that – I assume – could be later used to clone somewhere else. However, since it does not come from a restriction reaction, ligation would not happen without a 5'-phosphate. Are these taken into account in `ShareYourCloning` or `pydna`?

In any case, to implement the latter case, we need to add the overhang and it will not work with the current implementation. Should we cover this case now or leave it for later? Any suggestion on how?

**Comment by manulera** [comment]
> So the resulting DNA would have this overhang that – I assume – could be later used to clone somewhere else. However, since it does not come from a restriction reaction, ligation would not happen without a 5'-phosphate. Are these taken into account in `ShareYourCloning` or `pydna`?

That's what I imagined as well. Regarding phosphates, these are not handled by pydna as far as I know, and I don't think we should get into that, at least for now.

As to what should happen with the assembly class in a case like this, I would say the assembly method where this is picked up can raise a not implemented exception if there is this type of overhang. In the API you could catch this error and return a 400 error to the frontend. What do you think?

**Comment by manulera** [comment]
Hi @dgruano I am back! Should I finish these tests myself?

**Comment by dgruano** [comment]
Hi there!

I think I have created some tests, but not pushed them to the branch. Let
me push my latest changes tonight, and you can then wrap it up!

**Comment by manulera** [comment]
Great, just a heads-up, tests may fail when you push the branch. It's a problem in seguid versions that is fixed in #114. You can push your changes and I will handle the merge.

**Comment by manulera** [comment]
Hi @dgruano, I gave it a long thought today and I concluded that implementing it as an assembly might not have been the best idea, sorry about that. As far as I can think of, there are three possible cases, shown in the image below:




1. "Normal" templateless PCR.
2. Templateless PCR where polymerisation can only happen on one of the sides (like the last test case).
3. Simple hybridization of the primers without PCR, since the overhangs are only at the 5' ends.

I realise that one may also want to simply make a sequence of DNA with overhangs by hybridizing 2 oligos, and not do a PCR. Perhaps then what makes more sense is to have two types of sources:

* Oligo hybridization
* Polymerase fill-in (or similar name)

Also, the polymerase fill-in can then be used in other cases to fill overhangs (not sure when this would be useful, but who knows).

For the frontend, I could make the templateless PCR call one endpoint after the other, and re-use the current interface, if that makes sense?

This is how an example of the hybridization looks:

```python
{
    'source': {
        'id': 1,
        'kind': 'source',
        'input': [],
        'output': 0,
        'type': 'oligonucleotide_hybridization',
        'forward_oligo': 2,
        'reverse_oligo': 3,
    },
    'primers': [
        {'id': 2, 'name': 'primer1', 'sequence': 'aaGCGGCCGCgtagaactttatgtgcttccttacattggt'},
        {'id': 3, 'name': 'primer2', 'sequence': 'aaGCGGCCGCaccaatgtaaggaagcacataaagttctac'},
    ],
},

```

**Comment by dgruano** [comment]
Hi @manulera !

Everything you say makes sense. After getting to know a bit more the guts of `pydna`, it is true that using an Assembly seems artificial. I agree with your use cases, and I think that adding two different endpoints is the way to go to reuse code!

Looking forward to seeing it in production!

**Comment by manulera** [comment]
This is finished now. Thanks @dgruano for the contribution and feedback. Will put it in the production site soon.

In the end, it was not really easy to do in one step two sources because of how the frontend code is organised, and how the `useBackendAPI` hook works (it was written so that one call the backend API would would update the tree, so it's not straightforward to do two calls.

I put an example "Templateless PCR" anyway, where you can see that first you have to hybridize, then fill-in with the polymerase.

**Pull request merged**
