### PR TITLE
Add support for CRISPR homology-directed repair (WIP)

### PR DESCRIPTION
**Pull request by dgruano**
Hi @manulera !

Following our discussion on #102 , I implemented some basic functionality to use CRISPR. It follows the same logic as standard Homologous Recombination, but checks that the Cas9 cut occurs within the homology region.

I added a file with an example cloning strategy with template, insert and guide to test CRISPR in the app, `crispr_test.json`.

We just need to find a nice way to add tests for edge cases. I did quick and dirty tests in the `crispr.ipynb` notebook, but I have not found a way to properly implement them just yet. This is because the tests use a hypothetical Cas9 enzyme with a 5 bp guide (makes it easy to design the sequences for the tests), but the current version of the endpoint uses a hardcoded standard Cas9 with 20 bp guide. We could:
- Design appropriate example sequences to test the 20 bp Cas9.
- Wait until we allow for custom Cas enzymes (if this is the case)

Let me know your thoughts.
Cheers!

### CODE REVIEW

**Comment by manulera** [comment]
Hi @dgruano, I have added a few basic tests and refactored a bit. The most important change is that now you can add more than one guide RNA to be passed. 

I can add for the tests cases you mentioned, but I have some questions about specific cases and what should happen to them:

Ex1 / Ex2: Not sure what should happen here. Here the homology region would clearly be too short, perhaps if the cut falls on top the homology region, it should only be allowed if the remaining homology arm is >= minimal_homology.

```
EX1: Cut on the right part of HR
        ><
       GTaaaPAM
       |||||
ACGtttGGTAAAAGGACGT
|||    |||
ACG....GTA

EX2: Cut on the left part of HR
 ><
ACGttPAM  
|||||
ACGttAGGCTGCA
 |||  |||
 CGT..GGC
```

EX4: This would be a no for me, I would say.
```

EX4: Cut to the left of HR
     ><
    GTaaaPAM
    |||||PAM
TTTGGTaaaAGGACGT
      |||   |||
      AAA...ACG
```

EX5: I did not see the difference between this and EX4

```
EX5: Double target HR
        ><
       GTaaaPAM
       |||||
ACGtttGGTAAAAGGTGCA
|||   |||
ACG...GGT
```

**Comment by manulera** [comment]
I will merge this, since it has some minimal functionality, but I keep the issue open to add the tests.

**Comment by dgruano** [comment]
Hi @manulera , great!

For Ex1/Ex2, I agree. The cloning strategy needs to have minimal homology in both sides of the cut, so I would add that limitation.

Ex4 should not work as the homology region does not span over both sides of the cut.

Ex5 is a special case because the right side of the insert is homologous to two different sections of the template. Here is a more clear representation:

```
EX5: Double target HR
        ><
       GTaaaPAM
       |||||
ACGtttGGTAAAAGGTGCA
|||   |||
ACG...GGT (HR1)
|||          |||
ACG..........GGT (HR2)
```

In this example, using HR2 homology regions, the cut happens between them and can be repaired.

PS: Great addition to allow for multiple guides! Looking forward to test it.

**Comment by manulera** [comment]
This is now added in the hosted version, thanks @dgruano

**Pull request merged**
